Alter table ecommerce_orders
add constraint primary_key primary key(order_id);

CREATE UNIQUE CLUSTERED INDEX payment_id_index
ON ecommerce_payments(payment_id)
INCLUDE(order_id,final_amount);

-- 1. Find the total sales generated by each region after removing discount.
select eo.region,round(sum(ep.final_amount),2) as total_sales
from ecommerce_orders as eo
left join ecommerce_payments as ep
on eo.order_id = ep.order_id
group by eo.region
order by total_sales desc;

-- 2. Find the top 3 product categories by total sales.
select eo.product_category,round(sum(ep.final_amount),2) as total_sales
from ecommerce_orders as eo
left join ecommerce_payments as ep
on eo.order_id = ep.order_id
group by eo.product_category
order by total_sales desc
limit 3;

-- 3. Calculate average sales amount for each category.
select eo.product_category,round(avg(ep.final_amount),2) as total_sales
from ecommerce_orders as eo
left join ecommerce_payments as ep
on eo.order_id = ep.order_id
group by eo.product_category
order by total_sales desc;

-- 4. Find customers whose sales are greater than the average sales.
select * 
from ecommerce_orders
where sales_amount > (select round(avg(final_amount),2) from ecommerce_payments);

1. Find Top 3 Highest Sales Orders in Each Region
select * from (select 
region,
sales_amount,
dense_rank() over(partition by region order by sales_amount desc) as rnk
from ecommerce_orders)
where rnk <= 3;

-- 2. Find Customers Whose Order Amount is Greater Than Average Order Amount of Their Region
SELECT 
    order_id,
    customer_name,
    region,
    sales_amount
FROM ecommerce_orders e
WHERE sales_amount >
(
    SELECT AVG(sales_amount)
    FROM ecommerce_orders
    WHERE region = e.region
);

-- 3. Find Total Revenue Generated by Successful Payments Only
select sum(final_amount) as total_revenue
from ecommerce_payments
where payment_status = "Success";

-- 4. Find Region-wise Contribution Percentage to Overall Sales
select region,round(sum(final_amount) *100/sum(sum(final_amount)) over(),2)as percentage
from ecommerce_orders as eo
left join ecommerce_payments as ep
on eo.order_id = ep.order_id
group by region
order by percentage desc;

-- 5. Find Consecutive Orders Made on Same Date in Same Region
SELECT 
    region,
    order_date,
    COUNT(*) AS total_orders
FROM ecommerce_orders
GROUP BY region, order_date
HAVING COUNT(*) > 1;

-- 6. Find Customers Who Purchased Electronics More Than Once
select customer_id,count(product_category) as counter
from ecommerce_orders
where product_category = 'Electronics'
group by customer_id
having count(product_category) > 1;

-- 7. Find Payment Failure Percentage
select round(count(*) * 100/(select count(*) from ecommerce_payments),2) as Percentage
from ecommerce_payments
where payment_status = "Failed";

-- 8. Find Top 2 Highest Discount Given in Each Payment Method
select * from (select order_id,payment_method,final_amount,discount_amount,dense_rank() over(partition by payment_method order by discount_amount desc) as rnk
from ecommerce_payments)
where rnk <= 2;

-- 9. Find Monthly Running Revenue
select payment_date,sum(final_amount) over(partition by month(payment_date) order by payment_date)
from ecommerce_payments
where payment_status = "Success"

-- 10. Find Employees Earning More Than Department Average Salary
select o.emp_name,o.monthly_salary,e.department, e.dep_avg from (select department,round(avg(monthly_salary),2) as dep_avg
from employee_performance 
group by department) as e
join employee_performance as o
on e.department = o.department
where o.monthly_salary > e.dep_avg
order by o.monthly_salary desc,o.department asc;

-- 11. Find Second Highest Salary in Each Department
select * from (select emp_name,department,monthly_salary,
dense_rank() over(partition by department order by monthly_salary desc) as rnk
from employee_performance) 
where rnk = 2;

-- 12. Find Employees With Performance Score Above Department Average
select o.emp_name,o.performance_score,e.department,e.per_avg from (select department,round(avg(performance_score),2) as per_avg
from employee_performance
group by department) as e
join employee_performance as o
on e.department = o.department
where o.performance_score > e.per_avg;

-- 13. Find Department Having Highest Average Performance Score
select department,round(avg(performance_score),2) as avg_score
from employee_performance
group by department
order by avg_score desc
limit 1

-- 14. Find Employees Joined in Last 3 Years
SELECT 
    emp_name,
    joining_date
FROM employee_performance
WHERE joining_date >= CURRENT_DATE - INTERVAL '3 years';

-- 15. Find Salary Difference Between Current Employee and Previous Employee in Same Department
select emp_name,department,monthly_salary,
lag(monthly_salary) over(partition by department order by monthly_salary) as previous_sal,
monthly_salary - previous_sal as difference
from employee_performance;

-- 16. Find Top Performing Employee in Every Location
select * from(select emp_name,department,location,
dense_rank() over(partition by location order by performance_score desc) as r
from employee_performance)
where r = 1

-- 17. Find Customers Whose Final Amount is Less Than 90% of Original Sales Amount
SELECT o.order_id,o.customer_name,o.sales_amount,p.final_amount
FROM ecommerce_orders o
JOIN ecommerce_payments p
ON o.order_id = p.order_id
WHERE p.final_amount < o.sales_amount * 0.9;

-- 18. Find Average Discount Given Per Product Category
select eo.product_category,round(avg(ep.discount_amount),2)
from ecommerce_orders as eo
join ecommerce_payments as ep
on eo.order_id = ep.order_id
group by eo.product_category;

-- 19. Find Employees Whose Salary is Increasing Order-wise Within Department
select emp_name,department,monthly_salary,
row_number() over(partition by department order by monthly_salary) as rn
from employee_performance;

-- 20. Find Region-wise Most Popular Product Category
SELECT *
FROM (SELECT region,product_category,COUNT(*) AS total_orders,ROW_NUMBER() OVER(PARTITION BY region ORDER BY COUNT(*) DESC ) AS rn
FROM ecommerce_orders
GROUP BY region, product_category
) t
WHERE rn = 1;

-- 21. Find Day-wise Revenue Trend
SELECT payment_date,SUM(final_amount) AS daily_revenue
FROM ecommerce_payments
WHERE payment_status = 'Success'
GROUP BY payment_date
ORDER BY payment_date;
